"idfheoiruyg hnaeirlghomeirdddddddddddddddddddddddddddddddddddddddddgh iegrhcmierhglmekughoneiygnoieryf hvnksludfjtjfvslmcuedrhnktudvfajpmocerlusvgkfhdla;mclshrenihtvflemcsrhgesrihvmeoiretufolikrlnjvmevrltsyfhnaiomelrtuvnfwlmeckrhvtvnwmerhtgfvbj;namecritlhbpnvemrcpiltbhgsnlviruhfgbnvemuglkesrjtbgpsnvoemirtgmcirgidfheoiruyg hnaeirlghomeirdddddddddddddddddddddddddddddddddddddddddgh iegrhcmierhglmekughoneiygnoieryf hvnksludfjtjfvslmcuedrhnktudvfajpmocerlusvgkfhdla;mclshrenihtvflemcsrhgesrihvmeoiretufolikrlnjvmevrltsyfhnaiomelrtuvnfwlmeckrhvtvnwmerhtgfvbj;namecritlhbpnvemrcpiltbhgsnlviruhfgbnvemuglkesrjtbgpsnvoemirtgmcirgidfheoiruyg hnaeirlghomeirdddddddddddddddddddddddddddddddddddddddddgh iegrhcmierhglmekughoneiygnoieryf hvnksludfjtjfvslmcuedrhnktudvfajpmocerlusvgkfhdla;mclshrenihtvflemcsrhgesrihvmeoiretufolikrlnjvmevrltsyfhnaiomelrtuvnfwlmeckrhvtvnwmerhtgfvbj;namecritlhbpnvemrcpiltbhgsnlviruhfgbnvemuglkesrjtbgpsnvoemirtgmcirgidfheoiruyg hnaeirlghomeirdddddddddddddddddddddddddddddddddddddddddgh iegrhcmierhglmekughoneiygnoieryf hvnksludfjtjfvslmcuedrhnktudvfajpmocerlusvgkfhdla;mclshrenihtvflemcsrhgesrihvmeoiretufolikrlnjvmevrltsyfhnaiomelrtuvnfwlmeckrhvtvnwmerhtgfvbj;namecritlhbpnvemrcpiltbhgsnlviruhfgbnvemuglkesrjtbgpsnvoemirtgmcirg"
"!@##$%^&*(){}:"
"string_123"
"Hello\
World"
"Hello
World"
a <- 123
c=-12
b = -1
A_345
"A_345" -- a line comment
B_42
(* A comment *)
B_43
(* this is a multiline comment (*sdfsdf*)
 *)
Case ESAC
CLASS class CLass
true 
fALSe
a = 1

out_string("\vTo add a number to ");
