"idfheoiruyg hnaeirlghomeirdddddddddddddddddddddddddddddddddddddddddgh iegrhcmierhglmekughoneiygnoieryf hvnksludfjtjfvslmcuedrhnktudvfajpmocerlusvgkfhdla;mclshrenihtvflemcsrhgesrihvmeoiretufolikrlnjvmevrltsyfhnaiomelrtuvnfwlmeckrhvtvnwmerhtgfvbj;namecritlhbpnvemrcpiltbhgsnlviruhfgbnvemuglkesrjtbgpsnvoemirtgmcirgidfheoiruyg hnaeirlghomeirdddddddddddddddddddddddddddddddddddddddddgh iegrhcmierhglmekughoneiygnoieryf hvnksludfjtjfvslmcuedrhnktudvfajpmocerlusvgkfhdla;mclshrenihtvflemcsrhgesrihvmeoiretufolikrlnjvmevrltsyfhnaiomelrtuvnfwlmeckrhvtvnwmerhtgfvbj;namecritlhbpnvemrcpiltbhgsnlviruhfgbnvemuglkesrjtbgpsnvoemirtgmcirgidfheoiruyg hnaeirlghomeirdddddddddddddddddddddddddddddddddddddddddgh iegrhcmierhglmekughoneiygnoieryf hvnksludfjtjfvslmcuedrhnktudvfajpmocerlusvgkfhdla;mclshrenihtvflemcsrhgesrihvmeoiretufolikrlnjvmevrltsyfhnaiomelrtuvnfwlmeckrhvtvnwmerhtgfvbj;namecritlhbpnvemrcpiltbhgsnlviruhfgbnvemuglkesrjtbgpsnvoemirtgmcirgidfheoiruyg hnaeirlghomeirdddddddddddddddddddddddddddddddddddddddddgh iegrhcmierhglmekughoneiygnoieryf hvnksludfjtjfvslmcuedrhnktudvfajpmocerlusvgkfhdla;mclshrenihtvflemcsrhgesrihvmeoiretufolikrlnjvmevrltsyfhnaiomelrtuvnfwlmeckrhvtvnwmerhtgfvbj;namecritlhbpnvemrcpiltbhgsnlviruhfgbnvemuglkesrjtbgpsnvoemirtgmcirg"
"!@##$%^&*(){}:"
"string_123"
"Hello\
World"
"Hello
World"
-123
123
A_345
"A_345" -- a line comment
B_42
(* A comment *)
B_43
(* this is a multiline comment (*sdfsdf*)
 *)
Case ESAC
CLASS class CLass
true 
fALSe
a = 1
